# Generated by Django 3.2.3 on 2021-05-28 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid_helper', '0002_auto_20210529_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='timeStamp',
            new_name='timestamp',
        ),
    ]
