# Generated by Django 3.2.3 on 2021-05-28 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid_helper', '0003_rename_timestamp_contact_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='timestamp',
        ),
    ]
