# Generated by Django 3.2.3 on 2021-05-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_name_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='requirment',
        ),
        migrations.AddField(
            model_name='post',
            name='age',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
