# Generated by Django 3.2.3 on 2021-05-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210529_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default='', max_length=129),
            preserve_default=False,
        ),
    ]
