# Generated by Django 3.0.6 on 2021-05-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=80)),
                ('business_email', models.EmailField(max_length=254)),
                ('business_website', models.CharField(max_length=80)),
                ('business_phone', models.CharField(max_length=80)),
            ],
        ),
    ]
