# Generated by Django 3.0.6 on 2021-05-29 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_listing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
